[book]
title = "Rust 학습 가이드"
authors = ["Byunghoon Kang"]
language = "ko"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kang-byunghoon/rust-study"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
boost-hierarchy = 2

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.fold]
enable = true
level = 0
